/* This file is generated by running `pnpm run swizzle @docusaurus/theme-classic DocItem/Layout --eject` after which we:
- add `eslint-disable-next-line @typescript-eslint/no-unused-vars, no-unused-vars` for the React import.
- swap `@theme-original/` for `@theme-original/` which is the official Docusaurus theme alias for the original theme.
- modify the `ContentVisibility` logic to only show in development mode.
- run linting.
- add `@ts-expect-error` to line to ignore ts-errors in original Docusaurus code.
Read more on Docusaurus swizzling: https://docusaurus.io/docs/swizzling
*/

// eslint-disable-next-line @typescript-eslint/no-unused-vars, no-unused-vars
import React, { type ReactNode } from 'react';
import clsx from 'clsx';
import { useWindowSize } from '@docusaurus/theme-common';
import { useDoc } from '@docusaurus/plugin-content-docs/client';
import DocItemPaginator from '@theme-original/DocItem/Paginator';
import DocVersionBanner from '@theme-original/DocVersionBanner';
import DocVersionBadge from '@theme-original/DocVersionBadge';
import DocItemFooter from '@theme-original/DocItem/Footer';
import DocItemTOCMobile from '@theme-original/DocItem/TOC/Mobile';
import DocItemTOCDesktop from '@theme-original/DocItem/TOC/Desktop';
import DocItemContent from '@theme-original/DocItem/Content';
import DocBreadcrumbs from '@theme-original/DocBreadcrumbs';
import ContentVisibility from '@theme-original/ContentVisibility';
import type { Props } from '@theme-original/DocItem/Layout';

import styles from './styles.module.css';

/**
 * Decide if the toc should be rendered, on mobile or desktop viewports
 */
function useDocTOC() {
  const { frontMatter, toc } = useDoc();
  const windowSize = useWindowSize();

  const hidden = frontMatter.hide_table_of_contents;
  const canRender = !hidden && toc.length > 0;

  const mobile = canRender ? <DocItemTOCMobile /> : undefined;

  const desktop = canRender && (windowSize === 'desktop' || windowSize === 'ssr') ? <DocItemTOCDesktop /> : undefined;

  return {
    hidden,
    mobile,
    desktop,
  };
}

// @ts-expect-error Docusaurus theme type mismatch (virtual module typing)
export default function DocItemLayout({ children }: Props): ReactNode {
  const docTOC = useDocTOC();
  const { metadata } = useDoc();
  return (
    <div className="row">
      <div className={clsx('col', !docTOC.hidden && styles.docItemCol)}>
        {process.env.NODE_ENV === 'development' && <ContentVisibility metadata={metadata} />}
        <DocVersionBanner />
        <div className={styles.docItemContainer}>
          <article>
            <DocBreadcrumbs />
            <DocVersionBadge />
            {docTOC.mobile}
            <DocItemContent>{children}</DocItemContent>
            <DocItemFooter />
          </article>
          <DocItemPaginator />
        </div>
      </div>
      {docTOC.desktop && <div className="col col--3">{docTOC.desktop}</div>}
    </div>
  );
}
