version: 2

updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    reviewers:
      - "nl-design-system/kernteam-dependabot"
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "monthly"
    groups:
      patch-and-minor-dependencies:
        applies-to: "version-updates"
        update-types:
          - "patch"
          - "minor"
    versioning-strategy: "increase-if-necessary"
    open-pull-requests-limit: 20
    reviewers:
      - "nl-design-system/kernteam-dependabot"
