---
version: "3"
services:
  www:
    volumes:
      - ./build:/usr/local/apache2/htdocs/
      - ./static/.htaccess:/usr/local/apache2/htdocs/.htaccess
      - ./static/factsheets:/usr/local/apache2/htdocs/factsheets
      - ./httpd.conf:/usr/local/apache2/conf/httpd.conf
    build:
      dockerfile: httpd.Dockerfile
    ports:
      - "8080:80"
