---
version: "3"
services:
  www:
    volumes:
      - ./build:/usr/local/apache2/htdocs/
      - ./static/.htaccess:/usr/local/apache2/htdocs/.htaccess
      - ./httpd.conf:/usr/local/apache2/conf/httpd.conf
    image: httpd:2.4
    ports:
      - "8080:80"
