import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  handboek: [
    {
      type: 'category',
      label: 'Handboek',
      collapsible: false,
      className: 'sidebar__main-category',
      link: {
        type: 'generated-index',
        title: 'Handboek',
        slug: 'handboek',
        keywords: ['Handboek', 'Meedoen', 'overzicht'],
      },
      items: [
        { type: 'doc', id: 'handboek/introductie' },
        { type: 'doc', id: 'handboek/estafettemodel' },
        {
          type: 'category',
          label: 'Huisstijl vastleggen',
          description: 'Je huisstijl vastleggen als thema bij NL Design System? Hier vind je hoe je dat aanpakt.',
          link: {
            type: 'generated-index',
            title: 'Huisstijl vastleggen',
            slug: '/handboek/huisstijl-vastleggen/overzicht',
            keywords: ['huisstijl', 'design tokens', 'overzicht'],
          },
          items: [{ type: 'autogenerated', dirName: 'handboek/huisstijl-vastleggen' }],
        },
        {
          type: 'category',
          label: 'Componenten bijdragen',
          description:
            'Componenten bijdragen? Hier vind je waar we op letten en hoe je met een stappenplan aan de Definition of Done kan voldoen.',
          link: {
            type: 'generated-index',
            title: 'Componenten bijdragen',
            description:
              'Componenten bijdragen? Hier vind je waar we op letten en hoe je met een stappenplan aan de Definition of Done kan voldoen.',
            slug: '/handboek/component-bijdragen/overzicht',
            keywords: ['definition of done', 'overzicht'],
          },
          items: [{ type: 'autogenerated', dirName: 'handboek/component-bijdragen' }],
        },
        {
          type: 'category',
          label: 'Voor designers',
          description:
            'Mee designen aan NL Design System of gebruik maken van bestaande Figma componenten? Als designer vind je hier alle documentatie die je nodig hebt.',
          link: {
            type: 'generated-index',
            title: 'Voor designers',
            description:
              'Mee designen aan NL Design System of gebruik maken van bestaande Figma componenten? Als designer vind je hier alle documentatie die je nodig hebt.',
            slug: '/handboek/designer/overzicht',
            keywords: ['designers', 'overzicht'],
          },
          items: [{ type: 'autogenerated', dirName: 'handboek/designer' }],
        },
        {
          type: 'category',
          label: 'Voor developers',
          description:
            'Mee ontwikkelen aan NL Design System of gebruik maken van bestaande componenten? Als developer vind je hier alle documentatie die je nodig hebt om te beginnen.',
          link: {
            type: 'generated-index',
            title: 'Voor developers',
            description:
              'Mee ontwikkelen aan NL Design System of gebruik maken van bestaande componenten? Als developer vind je hier alle documentatie die je nodig hebt om te beginnen.',

            slug: '/handboek/developer/overzicht',
            keywords: ['developer', 'overzicht'],
          },
          items: [{ type: 'autogenerated', dirName: 'handboek/developer' }],
        },
        {
          type: 'category',
          label: 'Voor organisaties',
          link: {
            type: 'generated-index',
            title: 'Voor organisaties',
            slug: '/handboek/organisatie/overzicht',
            keywords: ['organisaties', 'overzicht'],
          },
          items: [{ type: 'autogenerated', dirName: 'handboek/organisatie' }],
        },
        // {
        //   type: 'category',
        //   label: 'Voor leveranciers',
        //   link: {
        //     type: 'generated-index',
        //     title: 'Voor leveranciers',
        //     slug: '/handboek/leverancier/',
        //     keywords: ['leveranciers', 'overzicht'],
        //   },
        //   items: [{ type: 'autogenerated', dirName: 'handboek/leverancier' }],
        // },
        // {
        //   type: 'category',
        //   label: 'Voor managers',
        //   link: {
        //     type: 'generated-index',
        //     title: 'Voor managers',
        //     slug: '/handboek/manager/overzicht',
        //     keywords: ['managers', 'overzicht'],
        //   },
        //   items: [{ type: 'autogenerated', dirName: 'handboek/manager' }],
        // },
        { type: 'doc', id: 'handboek/leverancier/introductie' },
        { type: 'doc', id: 'handboek/cms-developer/introductie' },
        { type: 'doc', id: 'handboek/manager/introductie' },
        {
          type: 'category',
          label: 'Baseline',
          link: {
            type: 'doc',
            id: 'baseline/README',
          },
          items: [{ type: 'autogenerated', dirName: 'baseline' }],
        },
        { type: 'doc', id: 'woordenlijst/README' },
      ],
    },
  ],
  richtlijnen: [
    {
      type: 'category',
      label: 'Richtlijnen',
      description:
        'Onze richtlijnen om te helpen met het ontwikkelen van begrijpelijke, gebruiksvriendelijke én toegankelijke online dienstverlening. Onze richtlijnen zijn zoveel mogelijk onderbouwd met gebruikersonderzoek.',
      collapsible: false,
      className: 'sidebar__main-category',
      link: {
        type: 'doc',
        id: 'richtlijnen/README',
      },
      items: [
        {
          type: 'doc',
          id: 'richtlijnen/README',
        },
        {
          type: 'category',
          label: 'Stijl',
          description: 'Onze richtlijnen voor een toegankelijke huisstijl en visueel ontwerp.',
          link: {
            type: 'doc',
            id: 'richtlijnen/stijl/README',
          },
          items: [{ type: 'autogenerated', dirName: 'richtlijnen/stijl' }],
        },
        {
          type: 'category',
          label: 'Content',
          link: {
            type: 'doc',
            id: 'richtlijnen/content/README',
          },
          items: [{ type: 'autogenerated', dirName: 'richtlijnen/content' }],
        },
        /*{
          type: 'category',
          label: 'Code',
          link: {
            type: 'doc',
            id: 'richtlijnen/code/README',
          },
          items: [{ type: 'autogenerated', dirName: 'richtlijnen/code' }],
        },*/
        {
          type: 'category',
          label: 'Formulieren',
          description: 'Onze richtlijnen voor inclusieve formulieren.',
          link: {
            type: 'doc',
            id: 'richtlijnen/formulieren/README',
          },
          items: [{ type: 'autogenerated', dirName: 'richtlijnen/formulieren' }],
        },
        {
          type: 'category',
          label: 'WCAG',
          description:
            "Hier proberen WCAG begrijpelijk uit te leggen en daardoor makkelijker toepasbaar te maken. Daarnaast staat beschreven hoe je webpagina's voor de verschillende succescriteria kunt testen.",
          link: {
            type: 'doc',
            id: 'wcag/README',
          },
          items: [{ type: 'autogenerated', dirName: 'wcag' }],
        },
        {
          type: 'category',
          label: 'Changelog',
          link: {
            type: 'doc',
            id: 'CHANGELOG',
          },
          items: [],
        },
      ],
    },
  ],
  componenten: [
    {
      type: 'category',
      label: 'Componenten',
      collapsible: false,
      className: 'sidebar__main-category',
      items: [{ type: 'autogenerated', dirName: 'componenten' }],
    },
  ],
  voorbeelden: [
    {
      type: 'category',
      label: 'Voorbeelden',
      collapsible: false,
      className: 'sidebar__main-category',
      description:
        "Hier tonen we voorbeelden van veelvoorkomende pagina's en klantreizen, gemaakt met richtlijnen en componenten uit NL Design System.",
      link: {
        type: 'doc',
        id: 'voorbeelden/introductie',
      },
      items: [
        { type: 'doc', id: 'voorbeelden/introductie' },
        { type: 'doc', id: 'voorbeelden/gebruikersonderzoek' },
        {
          type: 'category',
          label: 'Patronen en templates',
          link: {
            type: 'doc',
            id: 'voorbeelden/patronen-en-templates/overzicht',
          },
          items: [{ type: 'autogenerated', dirName: 'voorbeelden/patronen-en-templates' }],
        },
      ],
    },
  ],
  community: [
    {
      type: 'category',
      label: 'Community',
      collapsible: false,
      className: 'sidebar__main-category',
      link: {
        type: 'generated-index',
        title: 'Community',
        slug: 'community',
        keywords: ['Community', 'overzicht'],
      },
      items: [
        { type: 'doc', id: 'community/sluit-je-aan' },
        { type: 'doc', id: 'community/wie-doet-mee' },
        {
          type: 'category',
          label: 'Community Sprints',
          link: {
            type: 'doc',
            id: 'community/community-sprints/index',
          },
          items: [
            {
              type: 'doc',
              id: 'community/community-sprints/index',
            },
            {
              type: 'category',
              label: 'Overheidsbrede Portalen Community',
              description:
                'De Overheidsbrede Portalen Community Sprint maakt deel uit van een samenwerkingsverband om NL Design System-componenten te ontwikkelen voor projecten die moeten voldoen aan de Overheidsbrede Portalen.',
              link: {
                type: 'generated-index',
                title: 'Overheidsbrede Portalen Community',
                slug: 'community/community-sprints/overheidsbrede-portalen-community/overzicht',
              },
              items: [
                {
                  type: 'doc',
                  id: 'community/community-sprints/overheidsbrede-portalen-community/overheidsbrede-portalen-community',
                },
                { type: 'doc', id: 'community/community-sprints/overheidsbrede-portalen-community/aanmelden' },
              ],
            },
            {
              type: 'category',
              label: 'Rijkshuisstijl Community',
              description:
                'De Rijkshuisstijl Community Sprint maakt deel uit van een samenwerkingsverband om NL Design System-componenten te ontwikkelen voor projecten die moeten voldoen aan de Rijkshuisstijl.',
              link: {
                type: 'generated-index',
                title: 'Rijkshuisstijl Community',
                slug: 'community/community-sprints/rijkshuisstijl-community/overzicht',
              },
              items: [
                {
                  type: 'doc',
                  id: 'community/community-sprints/rijkshuisstijl-community/rijkshuisstijl-community',
                },
                { type: 'doc', id: 'community/community-sprints/rijkshuisstijl-community/aanmelden' },
              ],
            },
          ],
        },
        {
          type: 'category',
          label: 'Bijeenkomsten',
          description:
            'NL Design System organiseert regelmatig bijeenkomsten, online en offline, met als doel om samen te werken en kennis te delen.',
          collapsible: true,
          link: {
            type: 'generated-index',
            title: 'Bijeenkomsten',
            slug: '/community/events/overzicht',
          },
          items: [
            {
              type: 'category',
              label: 'Heartbeat',
              link: {
                type: 'generated-index',
                title: 'Heartbeat',
                slug: '/events/heartbeat/overzicht',
              },
              description:
                "In onze tweewekelijkse Heartbeat vertellen kernteam en community wat er gaande is. Meld je aan of kijk video's terug.",
              items: [
                { type: 'doc', id: 'community/events/heartbeat/heartbeat' },
                { type: 'doc', id: 'community/events/heartbeat/videos' },
                { type: 'doc', id: 'community/events/heartbeat/aanmelden' },
                { type: 'doc', id: 'community/events/heartbeat/zelf-iets-vertellen' },
              ],
            },
            {
              type: 'category',
              label: 'Design Open Hour',
              description:
                'Tijdens de (online) Design Open Hour delen designers van verschillende organisaties kennis.',
              link: {
                type: 'generated-index',
                title: 'Design Open Hour',
                slug: '/events/design-open-hour/overzicht',
              },
              items: [
                { type: 'doc', id: 'community/events/design-open-hour/design-open-hour' },
                { type: 'doc', id: 'community/events/design-open-hour/aanmelden' },
              ],
            },
            { type: 'doc', id: 'community/events/rijkshuisstijl-community-open-hour' },
            {
              type: 'category',
              label: 'Developer Open Hour',
              description:
                'Tijdens de (online) Developer Open Hour delen developers van verschillende organisaties kennis.',
              link: {
                type: 'generated-index',
                title: 'Developer Open Hour',
                slug: '/events/developer-open-hour/overzicht',
              },
              items: [
                { type: 'doc', id: 'community/events/developer-open-hour/developer-open-hour' },
                { type: 'doc', id: 'community/events/developer-open-hour/aanmelden' },
              ],
            },
            { type: 'doc', id: 'community/events/design-open-dag' },
            { type: 'doc', id: 'community/events/estafettemodeldag' },
          ],
        },
        {
          type: 'category',
          label: 'Design Systems Week',
          link: {
            type: 'doc',
            id: 'community/events/design-systems-week/index',
          },
          items: [
            { type: 'doc', id: 'community/events/design-systems-week/index' },
            {
              type: 'category',
              label: 'English',
              link: { type: 'doc', id: 'community/events/design-systems-week/en/index' },
              items: [
                { type: 'doc', id: 'community/events/design-systems-week/en/index' },
                {
                  type: 'category',
                  label: 'Previous editions',
                  link: { type: 'doc', id: 'community/events/design-systems-week/en/previous-editions/2024' },
                  items: [
                    { type: 'autogenerated', dirName: 'community/events/design-systems-week/en/previous-editions' },
                  ],
                },
              ],
            },
            {
              type: 'category',
              label: 'Eerdere edities',
              link: { type: 'doc', id: 'community/events/design-systems-week/eerdere-edities/2024' },
              items: [{ type: 'autogenerated', dirName: 'community/events/design-systems-week/eerdere-edities' }],
            },
          ],
        },
      ],
    },
  ],
  project: [
    {
      type: 'category',
      label: 'Project',
      collapsible: false,
      className: 'sidebar__main-category',
      link: {
        type: 'doc',
        id: 'project/README',
      },
      items: [
        { type: 'doc', id: 'project/over-nl-design-system' },
        { type: 'doc', id: 'project/faq' },
        { type: 'doc', id: 'project/kernteam' },
        { type: 'doc', id: 'project/blijf-op-de-hoogte' },
        { type: 'doc', id: 'project/links' },
        { type: 'doc', id: 'project/global-design-system' },
      ],
    },
  ],
};

export default sidebars;
