/**
// @ts-check
/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  richtlijnen: [{ type: 'autogenerated', dirName: 'richtlijnen' }],
  componenten: [{ type: 'autogenerated', dirName: 'componenten' }],
  patronen: [{ type: 'autogenerated', dirName: 'patronen' }],
  meedoen: [{ type: 'autogenerated', dirName: 'meedoen' }],
  aanpak: [{ type: 'autogenerated', dirName: 'aanpak' }],
  voorbeelden: [{ type: 'autogenerated', dirName: 'voorbeelden' }],
};

module.exports = sidebars;
