/**
// @ts-check
/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  algemeen: [{ type: "autogenerated", dirName: "algemeen" }],
  componenten: [{ type: "autogenerated", dirName: "componenten" }],
  patronen: [{ type: "autogenerated", dirName: "patronen" }],
  meedoen: [{ type: "autogenerated", dirName: "meedoen" }],
  voorbeelden: [{ type: "autogenerated", dirName: "voorbeelden" }],
};

module.exports = sidebars;
