export default {
  extends: ['stylelint-config-standard-scss'],
  ignoreFiles: ['node_modules', '**/dist/**/*', '**/coverage/**/*', 'src/**/*'],
  plugins: ['stylelint-order'],
  rules: {
    'alpha-value-notation': ['percentage'],
    'at-rule-empty-line-before': null,
    'at-rule-no-unknown': null,
    'block-no-empty': [true],
    'color-function-notation': ['modern'],
    'color-no-invalid-hex': [true],
    'comment-no-empty': [true],
    'custom-property-pattern': '^_?(denhaag|docusaurus|example|ifm|nl|nlds|utrecht|ma|basis)-[a-z0-9-]+$',
    'declaration-block-no-duplicate-properties': [true, { ignore: ['consecutive-duplicates-with-different-values'] }],
    'declaration-block-no-redundant-longhand-properties': null,
    'declaration-block-no-shorthand-property-overrides': [true],
    'declaration-property-value-disallowed-list': [
      {
        'text-align': ['left', 'right'],
      },
    ],
    'font-family-name-quotes': ['always-unless-keyword'],
    'font-family-no-duplicate-names': [true],
    'font-family-no-missing-generic-family-keyword': [true],
    'font-weight-notation': [
      'numeric',
      {
        ignore: ['relative'],
      },
    ],
    'function-calc-no-unspaced-operator': [true],
    'function-linear-gradient-no-nonstandard-direction': [true],
    'function-url-no-scheme-relative': [true],
    'function-url-quotes': ['always'],
    'hue-degree-notation': ['number'],
    'keyframe-declaration-no-important': [true],
    'keyframes-name-pattern': '^(denhaag|docusaurus|example|ifm|nl|nlds|utrecht|ma|basis)-[a-z0-9-]+$',
    'length-zero-no-unit': [
      true,
      {
        ignore: ['custom-properties'],
      },
    ],
    'media-feature-name-no-unknown': [true],
    'no-descending-specificity': [true],
    'no-duplicate-at-import-rules': [true],
    'no-duplicate-selectors': [true],
    'no-empty-source': [true],
    'no-invalid-double-slash-comments': [true],
    'order/order': ['custom-properties', 'declarations'],
    'order/properties-alphabetical-order': true,
    'property-disallowed-list': [
      [
        'border-bottom',
        'border-bottom-color',
        'border-bottom-left-radius',
        'border-bottom-right-radius',
        'border-bottom-style',
        'border-bottom-width',
        'border-left',
        'border-left-color',
        'border-left-style',
        'border-left-width',
        'border-right',
        'border-right-color',
        'border-right-style',
        'border-right-width',
        'border-top',
        'border-top-color',
        'border-top-left-radius',
        'border-top-right-radius',
        'border-top-style',
        'border-top-width',
        'bottom',
        'contain-intrinsic-height',
        'contain-intrinsic-width',
        'height',
        'left',
        'margin',
        'margin-bottom',
        'margin-left',
        'margin-right',
        'margin-top',
        'max-height',
        'max-width',
        'min-height',
        'min-width',
        'padding',
        'padding-bottom',
        'padding-left',
        'padding-right',
        'padding-top',
        'right',
        'scroll-margin-bottom',
        'scroll-margin-left',
        'scroll-margin-right',
        'scroll-margin-top',
        'scroll-padding-bottom',
        'scroll-padding-left',
        'scroll-padding-right',
        'scroll-padding-top',
        'top',
        'width',
      ],
    ],
    'property-no-unknown': [true],
    'property-no-vendor-prefix': null,
    'rule-empty-line-before': null,
    'scss/at-extend-no-missing-placeholder': null,
    'scss/at-mixin-pattern': '^[a-z][a-z0-9-_]*$',
    'scss/at-rule-no-unknown': true,
    'scss/dollar-variable-default': true,
    'scss/dollar-variable-first-in-block': [true, { ignore: ['comments', 'imports'] }],
    'scss/dollar-variable-pattern': '^(denhaag|docusaurus|example|ifm|nl|nlds|utrecht|ma|basis)-[a-z0-9-]+$',
    'scss/operator-no-newline-after': null,
    'scss/percent-placeholder-pattern': '^(denhaag|docusaurus|example|ifm|nl|nlds|utrecht|ma|basis)-[a-z0-9-]+$',
    'selector-attribute-quotes': ['always'],
    'selector-class-pattern': '^(denhaag|docusaurus|example|ifm|nl|nlds|utrecht|ma|basis)-[a-z0-9_-]+$',
    'selector-max-id': [0],
    'selector-pseudo-class-no-unknown': [true],
    'selector-pseudo-element-no-unknown': [true],
    'string-no-newline': [true],
    'unit-disallowed-list': [['s']],
    'unit-no-unknown': [true],
    'value-keyword-case': ['lower', { camelCaseSvgKeywords: true }],
  },
};
