export const issues = [
  { number: 1, label: 'Label niet gekoppeld' },
  { number: 2, label: 'Vragen om invoer te herhalen' },
  { number: 3, label: 'Haakje(s) voor afkorting(en)' },
  { number: 4, label: 'Taalgebruik niet hetzelfde' },
  { number: 5, label: 'Fout alleen met kleur aangegeven' },
  { number: 6, label: 'Vragen om onnodige informatie' },
  { number: 7, label: 'Geen gebruik van de optie voor automatisch invullen' },
  { number: 8, label: 'Alle velden zijn even lang' },
  { number: 9, label: 'Velden in kolommen of in een tabel' },
  { number: 10, label: 'Foutmelding voor je klaar bent met invoeren' },
  { number: 11, label: 'Geen uitleg waar contact gegevens voor nodig zijn' },
  { number: 12, label: 'Velden niet bereikbaar met een toetsenbord' },
  { number: 13, label: 'Onduidelijk waar de focus is' },
  { number: 14, label: 'Knoppen staan aan het einde van de regel' },
  { number: 15, label: 'Afkortingen en moeilijke woorden worden niet uitgelegd' },
  { number: 16, label: 'Belangrijke informatie zit verstopt' },
  { number: 17, label: 'Geldig antwoord wordt geweigerd' },
  { number: 18, label: 'Antwoord moet precies zoals de computer het verwacht' },
  { number: 19, label: 'Vertaal programma vertaalt antwoord op de controlepagina' },
  { number: 20, label: 'Foutmelding helpt niet om het antwoord goed in te vullen' },
  { number: 21, label: 'Onduidelijk welke antwoorden verplicht zijn' },
  { number: 22, label: 'Naam van veld of beschrijving van het veld slecht leesbaar' },
];
