name: publish

on:
  push:
    branches: main

permissions: {}

jobs:
  publish:
    runs-on: ubuntu-latest
    environment: publish
    permissions:
      contents: read # since GH_TOKEN is provided, we only need 'read'
      pull-requests: write # Needed to create and update pull requests
      id-token: write # https://docs.npmjs.com/generating-provenance-statements#publishing-packages-with-provenance-via-github-actions

    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          token: ${{ secrets.GH_TOKEN }}
          persist-credentials: true

      - name: Install pnpm package manager
        uses: pnpm/action-setup@0ebf47130e4866e96fce0953f49152a61190b271 # v6.0.9

      - name: Set up Node.js version and cache
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version-file: .nvmrc
          cache: pnpm

      - name: Check for known security issues with npm packages
        run: |
          echo "Auditing npm dependencies before installing them. For more information, see: https://nldesignsystem.nl/pnpm-audit"
          pnpm audit --audit-level critical

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Publish to the npm Registry
        uses: changesets/action@a45c4d594aa4e2c509dc14a9f2b3b67ba3780d0d # v1.9.0
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          GIT_AUTHOR_EMAIL: ${{ secrets.GIT_AUTHOR_EMAIL }}
          GIT_AUTHOR_NAME: "NL Design System"
          GIT_COMMITTER_EMAIL: ${{ secrets.GIT_COMMITTER_EMAIL }}
          GIT_COMMITTER_NAME: "NL Design System"
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        with:
          commit: "docs(release): design system packages"
          setupGitUser: false
          title: "docs(release): design system packages"
          publish: "pnpm run changeset:publish"
